
DROP TABLE IF EXISTS SignedUser CASCADE;
DROP TABLE IF EXISTS Song CASCADE;
DROP TABLE IF EXISTS Performer CASCADE;
DROP TABLE IF EXISTS Club CASCADE;
DROP TABLE IF EXISTS Chant CASCADE;
DROP TABLE IF EXISTS PerfSong CASCADE;
DROP TABLE IF EXISTS ClubChant CASCADE;